export enum SlotType {
  FIFTEEN_MINUTES = "FIFTEEN_MINUTES",
  THIRTY_MINUTES = "THIRTY_MINUTES",
  FORTY_MINUTES = "FORTY_MINUTES",
  FORTY_FIVE_MINUTES = "FORTY_FIVE_MINUTES",
  FIFTY_MINUTES = "FIFTY_MINUTES",
  HOUR = "HOUR",
  HOUR_AND_FIFTEEN = "HOUR_AND_FIFTEEN"
}
